# ARK creature ID data - auto-mapped from ark.wiki.gg/wiki/Creature_IDs.

# Creature wiki data (auto-mapped from ark.wiki.gg/wiki/Creature_IDs)
# name -> (entity_id, name_tag, blueprint_path)
# =============================================================================
_CREATURE_DATA: dict[str, tuple[str, str, str]] = {
    'Aberrant Achatina': ('Achatina_Character_BP_Aberrant_C', 'Achatina', "Blueprint'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP_Aberrant.Achatina_Character_BP_Aberrant'"),
    'Aberrant Anglerfish': ('Angler_Character_BP_Aberrant_C', 'Angler', "Blueprint'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP_Aberrant.Angler_Character_BP_Aberrant'"),
    'Aberrant Ankylosaurus': ('Ankylo_Character_BP_Aberrant_C', 'Anky', "Blueprint'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP_Aberrant.Ankylo_Character_BP_Aberrant'"),
    'Aberrant Araneo': ('SpiderS_Character_BP_Aberrant_C', 'Spider', "Blueprint'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP_Aberrant.SpiderS_Character_BP_Aberrant'"),
    'Aberrant Arthropluera': ('Arthro_Character_BP_Aberrant_C', 'Arthro', "Blueprint'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP_Aberrant.Arthro_Character_BP_Aberrant'"),
    'Aberrant Baryonyx': ('Baryonyx_Character_BP_Aberrant_C', 'Baryonyx', "Blueprint'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP_Aberrant.Baryonyx_Character_BP_Aberrant'"),
    'Aberrant Beelzebufo': ('Toad_Character_BP_Aberrant_C', 'Toad', "Blueprint'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP_Aberrant.Toad_Character_BP_Aberrant'"),
    'Aberrant Carbonemys': ('Turtle_Character_BP_Aberrant_C', 'Turtle', "Blueprint'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP_Aberrant.Turtle_Character_BP_Aberrant'"),
    'Aberrant Carnotaurus': ('Carno_Character_BP_Aberrant_C', 'Carno', "Blueprint'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP_Aberrant.Carno_Character_BP_Aberrant'"),
    'Aberrant Cnidaria': ('Cnidaria_Character_BP_Aberrant_C', 'Cnidaria', "Blueprint'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP_Aberrant.Cnidaria_Character_BP_Aberrant'"),
    'Aberrant Coelacanth': ('Coel_Character_BP_Aberrant_C', 'Coel', "Blueprint'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP_Aberrant.Coel_Character_BP_Aberrant'"),
    'Aberrant Dimetrodon': ('Dimetro_Character_BP_Aberrant_C', 'Dimetro', "Blueprint'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP_Aberrant.Dimetro_Character_BP_Aberrant'"),
    'Aberrant Dimorphodon': ('Dimorph_Character_BP_Aberrant_C', 'Dimorph', "Blueprint'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP_Aberrant.Dimorph_Character_BP_Aberrant'"),
    'Aberrant Diplocaulus': ('Diplocaulus_Character_BP_Aberrant_C', 'Diplocaulus', "Blueprint'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP_Aberrant.Diplocaulus_Character_BP_Aberrant'"),
    'Aberrant Diplodocus': ('Diplodocus_Character_BP_Aberrant_C', 'Diplo', "Blueprint'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP_Aberrant.Diplodocus_Character_BP_Aberrant'"),
    'Aberrant Dire Bear': ('Direbear_Character_BP_Aberrant_C', 'Direbear', "Blueprint'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP_Aberrant.Direbear_Character_BP_Aberrant'"),
    'Aberrant Dodo': ('Dodo_Character_BP_Aberrant_C', 'Dodo', "Blueprint'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP_Aberrant.Dodo_Character_BP_Aberrant'"),
    'Aberrant Doedicurus': ('Doed_Character_BP_Aberrant_C', 'Doed', "Blueprint'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP_Aberrant.Doed_Character_BP_Aberrant'"),
    'Aberrant Dung Beetle': ('DungBeetle_Character_BP_Aberrant_C', 'Beetle', "Blueprint'/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_Character_BP_Aberrant.DungBeetle_Character_BP_Aberrant'"),
    'Aberrant Electrophorus': ('Eel_Character_BP_Aberrant_C', 'Eel', "Blueprint'/Game/PrimalEarth/Dinos/Eel/Eel_Character_BP_Aberrant.Eel_Character_BP_Aberrant'"),
    'Aberrant Equus': ('Equus_Character_BP_Aberrant_C', 'Equus', "Blueprint'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP_Aberrant.Equus_Character_BP_Aberrant'"),
    'Aberrant Fasolasuchus': ('Fasola_Character_BP_Aberrant_C', 'Fasola', "Blueprint'/Game/ASA/Dinos/Fasolasuchus/Fasola_Character_BP_Aberrant.Fasola_Character_BP_Aberrant'"),
    'Aberrant Gigantopithecus': ('Bigfoot_Character_BP_Aberrant_C', 'Bigfoot', "Blueprint'/Game/PrimalEarth/Dinos/Bigfoot/Bigfoot_Character_BP_Aberrant.Bigfoot_Character_BP_Aberrant'"),
    'Aberrant Gigantoraptor': ('Gigantoraptor_Character_BP_Aberrant_C', 'Gigantoraptor', "Blueprint'/Game/ASA/Dinos/Gigantoraptor/Gigantoraptor_Character_BP_Aberrant.Gigantoraptor_Character_BP_Aberrant'"),
    'Aberrant Iguanodon': ('Iguanodon_Character_BP_Aberrant_C', 'Iguanodon', "Blueprint'/Game/PrimalEarth/Dinos/Iguanodon/Iguanodon_Character_BP_Aberrant.Iguanodon_Character_BP_Aberrant'"),
    'Aberrant Lystrosaurus': ('Lystro_Character_BP_Aberrant_C', 'Lystro', "Blueprint'/Game/PrimalEarth/Dinos/Lystrosaurus/Lystro_Character_BP_Aberrant.Lystro_Character_BP_Aberrant'"),
    'Aberrant Manta': ('Manta_Character_BP_Aberrant_C', 'Manta', "Blueprint'/Game/PrimalEarth/Dinos/Manta/Manta_Character_BP_Aberrant.Manta_Character_BP_Aberrant'"),
    'Aberrant Megalania': ('Megalania_Character_BP_Aberrant_C', 'Megalania', "Blueprint'/Game/PrimalEarth/Dinos/Megalania/Megalania_Character_BP_Aberrant.Megalania_Character_BP_Aberrant'"),
    'Aberrant Megalosaurus': ('Megalosaurus_Character_BP_Aberrant_C', 'Megalosaurus', "Blueprint'/Game/PrimalEarth/Dinos/Megalosaurus/Megalosaurus_Character_BP_Aberrant.Megalosaurus_Character_BP_Aberrant'"),
    'Aberrant Meganeura': ('Dragonfly_Character_BP_Aberrant_C', 'Dragonfly', "Blueprint'/Game/PrimalEarth/Dinos/Dragonfly/Dragonfly_Character_BP_Aberrant.Dragonfly_Character_BP_Aberrant'"),
    'Aberrant Moschops': ('Moschops_Character_BP_Aberrant_C', 'Moschops', "Blueprint'/Game/PrimalEarth/Dinos/Moschops/Moschops_Character_BP_Aberrant.Moschops_Character_BP_Aberrant'"),
    'Aberrant Otter': ('Otter_Character_BP_Aberrant_C', 'Otter', "Blueprint'/Game/PrimalEarth/Dinos/Otter/Otter_Character_BP_Aberrant.Otter_Character_BP_Aberrant'"),
    'Aberrant Oviraptor': ('Oviraptor_Character_BP_Aberrant_C', 'Oviraptor', "Blueprint'/Game/PrimalEarth/Dinos/Oviraptor/Oviraptor_Character_BP_Aberrant.Oviraptor_Character_BP_Aberrant'"),
    'Aberrant Ovis': ('Sheep_Character_BP_Aberrant_C', 'Sheep', "Blueprint'/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP_Aberrant.Sheep_Character_BP_Aberrant'"),
    'Aberrant Paraceratherium': ('Paracer_Character_BP_Aberrant_C', 'Paracer', "Blueprint'/Game/PrimalEarth/Dinos/Paraceratherium/Paracer_Character_BP_Aberrant.Paracer_Character_BP_Aberrant'"),
    'Aberrant Parasaur': ('Para_Character_BP_Aberrant_C', 'Para', "Blueprint'/Game/PrimalEarth/Dinos/Para/Para_Character_BP_Aberrant.Para_Character_BP_Aberrant'"),
    'Aberrant Piranha': ('Piranha_Character_BP_Aberrant_C', 'Piranha', "Blueprint'/Game/PrimalEarth/Dinos/Piranha/Piranha_Character_BP_Aberrant.Piranha_Character_BP_Aberrant'"),
    'Aberrant Pulmonoscorpius': ('Scorpion_Character_BP_Aberrant_C', 'Scorpion', "Blueprint'/Game/PrimalEarth/Dinos/Scorpion/Scorpion_Character_BP_Aberrant.Scorpion_Character_BP_Aberrant'"),
    'Aberrant Purlovia': ('Purlovia_Character_BP_Aberrant_C', 'Purlovia', "Blueprint'/Game/PrimalEarth/Dinos/Purlovia/Purlovia_Character_BP_Aberrant.Purlovia_Character_BP_Aberrant'"),
    'Aberrant Raptor': ('Raptor_Character_BP_Aberrant_C', 'Raptor', "Blueprint'/Game/PrimalEarth/Dinos/Raptor/Raptor_Character_BP_Aberrant.Raptor_Character_BP_Aberrant'"),
    'Aberrant Sabertooth Salmon': ('Salmon_Character_Aberrant_C', 'Salmon', "Blueprint'/Game/PrimalEarth/Dinos/Salmon/Salmon_Character_Aberrant.Salmon_Character_Aberrant'"),
    'Aberrant Sarco': ('Sarco_Character_BP_Aberrant_C', 'Sarco', "Blueprint'/Game/PrimalEarth/Dinos/Sarco/Sarco_Character_BP_Aberrant.Sarco_Character_BP_Aberrant'"),
    'Aberrant Spino': ('Spino_Character_BP_Aberrant_C', 'Spino', "Blueprint'/Game/PrimalEarth/Dinos/Spino/Spino_Character_BP_Aberrant.Spino_Character_BP_Aberrant'"),
    'Aberrant Stegosaurus': ('Stego_Character_BP_Aberrant_C', 'Stego', "Blueprint'/Game/PrimalEarth/Dinos/Stego/Stego_Character_BP_Aberrant.Stego_Character_BP_Aberrant'"),
    'Aberrant Titanoboa': ('BoaFrill_Character_BP_Aberrant_C', 'Titanboa', "Blueprint'/Game/PrimalEarth/Dinos/BoaFrill/BoaFrill_Character_BP_Aberrant.BoaFrill_Character_BP_Aberrant'"),
    'Aberrant Triceratops': ('Trike_Character_BP_Aberrant_C', 'Trike', "Blueprint'/Game/PrimalEarth/Dinos/Trike/Trike_Character_BP_Aberrant.Trike_Character_BP_Aberrant'"),
    'Aberrant Trilobite': ('Trilobite_Character_Aberrant_C', 'Trilobite', "Blueprint'/Game/PrimalEarth/Dinos/Trilobite/Trilobite_Character_Aberrant.Trilobite_Character_Aberrant'"),
    'Achatina': ('Achatina_Character_BP_C', 'Achatina', "Blueprint'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP.Achatina_Character_BP'"),
    'Allosaurus': ('Allo_Character_BP_C', 'Allo', "Blueprint'/Game/PrimalEarth/Dinos/Allosaurus/Allo_Character_BP.Allo_Character_BP'"),
    'Alpha Basilisk': ('MegaBasilisk_Character_BP_C', 'Elite Basilisk', "Blueprint'/Game/Aberration/Dinos/Basilisk/MegaBasilisk_Character_BP.MegaBasilisk_Character_BP'"),
    'Alpha Blood Crystal Wyvern': ('CrystalWyvern_Character_BP_Mega_C', 'Wyvern', "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_Mega.CrystalWyvern_Character_BP_Mega'"),
    'Alpha Carno': ('MegaCarno_Character_BP_C', 'Elite Carno', "Blueprint'/Game/PrimalEarth/Dinos/Carno/MegaCarno_Character_BP.MegaCarno_Character_BP'"),
    'Alpha Deathworm': ('MegaDeathworm_Character_BP_C', 'Deathworm', "Blueprint'/Game/ScorchedEarth/Dinos/Deathworm/MegaDeathworm_Character_BP.MegaDeathworm_Character_BP'"),
    'Alpha Fire Wyvern': ('MegaWyvern_Character_BP_Fire_C', 'Wyvern', "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/MegaWyvern_Character_BP_Fire.MegaWyvern_Character_BP_Fire'"),
    'Alpha Karkinos': ('MegaCrab_Character_BP_C', 'Elite CaveCrab', "Blueprint'/Game/Aberration/Dinos/Crab/MegaCrab_Character_BP.MegaCrab_Character_BP'"),
    'Alpha King Titan': ('KingKaiju_Character_BP_Alpha_C', 'KingTitanAlpha', "Blueprint'/Game/Extinction/Dinos/KingKaiju/KingKaiju_Character_BP_Alpha.KingKaiju_Character_BP_Alpha'"),
    'Alpha Leedsichthys': ('Alpha_Leedsichthys_Character_BP_C', 'Leedsichthys', "Blueprint'/Game/PrimalEarth/Dinos/Leedsichthys/Alpha_Leedsichthys_Character_BP.Alpha_Leedsichthys_Character_BP'"),
    'Alpha Megalodon': ('MegaMegalodon_Character_BP_C', 'Elite Mega', "Blueprint'/Game/PrimalEarth/Dinos/Megalodon/MEgaMegalodon_Character_BP.MegaMegalodon_Character_BP'"),
    'Alpha Moeder, Master of the Ocean': ('EelBoss_Character_BP_Hard_C', 'EelBoss', "Blueprint'/Game/Genesis/Dinos/EelBoss/EelBoss_Character_BP_Hard.EelBoss_Character_BP_Hard'"),
    'Alpha Mosasaur': ('Mosa_Character_BP_Mega_C', 'Mosasaur', "Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP_Mega.Mosa_Character_BP_Mega'"),
    'Alpha Raptor': ('MegaRaptor_Character_BP_C', 'Elite Raptor', "Blueprint'/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_Character_BP.MegaRaptor_Character_BP'"),
    'Alpha Surface Reaper King': ('MegaXenomorph_Character_BP_Male_Surface_C', 'Elite Xenomorph', "Blueprint'/Game/Aberration/Dinos/Nameless/MegaXenomorph_Character_BP_Male_Surface.MegaXenomorph_Character_BP_Male_Surface'"),
    'Alpha T-Rex': ('MegaRex_Character_BP_C', 'Elite Rex', "Blueprint'/Game/PrimalEarth/Dinos/Rex/MegaRex_Character_BP.MegaRex_Character_BP'"),
    'Alpha Tusoteuthis': ('Mega_Tusoteuthis_Character_BP_C', 'Tusoteuthis', "Blueprint'/Game/PrimalEarth/Dinos/Tusoteuthis/Mega_Tusoteuthis_Character_BP.Mega_Tusoteuthis_Character_BP'"),
    'Alpha X-Triceratops': ('Volcano_Trike_Character_BP_Retrieve_Alpha_C', 'Trike', "Blueprint'/Game/Genesis/Dinos/MissionVariants/Retrieve/Volcanic/Volcano_Trike_Character_BP_Retrieve_Alpha.Volcano_Trike_Character_BP_Retrieve_Alpha'"),
    'Amargasaurus': ('Amargasaurus_Character_BP_C', 'Amarga', "Blueprint'/Game/LostIsland/Dinos/Amargasaurus/Amargasaurus_Character_BP.Amargasaurus_Character_BP'"),
    'Ammonite': ('Ammonite_Character_C', 'Ammonite', "Blueprint'/Game/PrimalEarth/Dinos/Ammonite/Ammonite_Character.Ammonite_Character'"),
    'Andrewsarchus': ('Andrewsarchus_Character_BP_C', 'Andrewsarchus', "Blueprint'/Game/Fjordur/Dinos/Andrewsarchus/Andrewsarchus_Character_BP.Andrewsarchus_Character_BP'"),
    'Anglerfish': ('Angler_Character_BP_C', 'Angler', "Blueprint'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP.Angler_Character_BP'"),
    'Ankylosaurus': ('Ankylo_Character_BP_C', 'Anky', "Blueprint'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP.Ankylo_Character_BP'"),
    'Araneo': ('SpiderS_Character_BP_C', 'Spider', "Blueprint'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP.SpiderS_Character_BP'"),
    'Archaeopteryx': ('Archa_Character_BP_C', 'Archa', "Blueprint'/Game/PrimalEarth/Dinos/Archaeopteryx/Archa_Character_BP.Archa_Character_BP'"),
    'Archelon': ('Archelon_Character_BP_ASA_C', 'Archelon', "Blueprint'/Game/ASA/Dinos/Archelon/Dinos/Archelon_Character_BP_ASA.Archelon_Character_BP_ASA'"),
    'Argentavis': ('Argent_Character_BP_C', 'Argent', "Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP'"),
    'Arthropluera': ('Arthro_Character_BP_C', 'Arthro', "Blueprint'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP.Arthro_Character_BP'"),
    'Astrocetus': ('SpaceWhale_Character_BP_C', 'Space Whale', "Blueprint'/Game/Genesis/Dinos/SpaceWhale/SpaceWhale_Character_BP.SpaceWhale_Character_BP'"),
    'Astrodelphis': ('SpaceDolphin_Character_BP_C', 'Astrodelphis', "Blueprint'/Game/Genesis2/Dinos/SpaceDolphin/SpaceDolphin_Character_BP.SpaceDolphin_Character_BP'"),
    'Baryonyx': ('Baryonyx_Character_BP_C', 'Baryonyx', "Blueprint'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP.Baryonyx_Character_BP'"),
    'Basilisk': ('Basilisk_Character_BP_C', 'Basilisk', "Blueprint'/Game/Aberration/Dinos/Basilisk/Basilisk_Character_BP.Basilisk_Character_BP'"),
    'Basilosaurus': ('Basilosaurus_Character_BP_C', 'Basilosaurus', "Blueprint'/Game/PrimalEarth/Dinos/Basilosaurus/Basilosaurus_Character_BP.Basilosaurus_Character_BP'"),
    'Beelzebufo': ('Toad_Character_BP_C', 'Toad', "Blueprint'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP.Toad_Character_BP'"),
    'Bison': ('Bison_Character_BP_C', 'Bison', "Blueprint'/Game/ASA/Dinos/Bison/Bison_Character_BP.Bison_Character_BP'"),
    'Blood Crystal Wyvern': ('CrystalWyvern_Character_BP_Blood_C', 'Wyvern', "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_Blood.CrystalWyvern_Character_BP_Blood'"),
    'Bloodstalker': ('BogSpider_Character_BP_C', 'Bloodstalker', "Blueprint'/Game/Genesis/Dinos/BogSpider/BogSpider_Character_BP.BogSpider_Character_BP'"),
    'Brontosaurus': ('Sauropod_Character_BP_C', 'Bronto', "Blueprint'/Game/PrimalEarth/Dinos/Sauropod/Sauropod_Character_BP.Sauropod_Character_BP'"),
    'Carbonemys': ('Turtle_Character_BP_C', 'Turtle', "Blueprint'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP.Turtle_Character_BP'"),
    'Carcharodontosaurus': ('Carcha_Character_BP_C', 'Carcha', "Blueprint'/Game/PrimalEarth/Dinos/Carcharodontosaurus/Carcha_Character_BP.Carcha_Character_BP'"),
    'Carnotaurus': ('Carno_Character_BP_C', 'Carno', "Blueprint'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP.Carno_Character_BP'"),
    'Castoroides': ('Beaver_Character_BP_C', 'Beaver', "Blueprint'/Game/PrimalEarth/Dinos/Beaver/Beaver_Character_BP.Beaver_Character_BP'"),
    'Ceratosaurus': ('Ceratosaurus_Character_BP_ASA_C', 'CeratosaurusAA', "Blueprint'/Game/ASA/Dinos/Ceratosaurus/Dinos/Ceratosaurus_Character_BP_ASA.Ceratosaurus_Character_BP_ASA'"),
    'Chalicotherium': ('Chalico_Character_BP_C', 'Chalicotherium', "Blueprint'/Game/PrimalEarth/Dinos/Chalicotherium/Chalico_Character_BP.Chalico_Character_BP'"),
    'Cnidaria': ('Cnidaria_Character_BP_C', 'Cnidaria', "Blueprint'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP.Cnidaria_Character_BP'"),
    'Coelacanth': ('Coel_Character_BP_C', 'Coel', "Blueprint'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP.Coel_Character_BP'"),
    'Compy': ('Compy_Character_BP_C', 'Compy', "Blueprint'/Game/PrimalEarth/Dinos/Compy/Compy_Character_BP.Compy_Character_BP'"),
    'Daeodon': ('Daeodon_Character_BP_C', 'Daeodon', "Blueprint'/Game/PrimalEarth/Dinos/Daeodon/Daeodon_Character_BP.Daeodon_Character_BP'"),
    'Deathworm': ('Deathworm_Character_BP_C', 'Deathworm', "Blueprint'/Game/ScorchedEarth/Dinos/DeathWorm/DeathWorm_Character_BP.DeathWorm_Character_BP'"),
    'Deinonychus': ('Deinonychus_Character_BP_C', 'Deinonychus', "Blueprint'/Game/PrimalEarth/Dinos/Raptor/Uberraptor/Deinonychus_Character_BP.Deinonychus_Character_BP'"),
    'Deinosuchus': ('Deinosuchusasa_Character_BP_C', 'DeinosuchusAA', "Blueprint'/Game/ASA/Dinos/Deinosuchus/Deinosuchusasa_Character_BP.Deinosuchusasa_Character_BP'"),
    'Deinotherium': ('DeinotheriumASA_Character_BP_C', 'DeinotheriumASA', "Blueprint'/Game/ASA/Dinos/Deinotherium/Dinos/DeinotheriumASA_Character_BP.DeinotheriumASA_Character_BP'"),
    'Desmodus': ('Desmodus_Character_BP_C', 'Desmodus', "Blueprint'/Game/Fjordur/Dinos/Desmodus/Desmodus_Character_BP.Desmodus_Character_BP'"),
    'Dilophosaur': ('Dilo_Character_BP_C', 'Dilo', "Blueprint'/Game/PrimalEarth/Dinos/Dilo/Dilo_Character_BP.Dilo_Character_BP'"),
    'Dimetrodon': ('Dimetro_Character_BP_C', 'Dimetro', "Blueprint'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP.Dimetro_Character_BP'"),
    'Dimorphodon': ('Dimorph_Character_BP_C', 'Dimorph', "Blueprint'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP.Dimorph_Character_BP'"),
    'Dinopithecus': ('Dinopithecus_Character_BP_C', 'Dinopithecus', "Blueprint'/Game/LostIsland/Dinos/Dinopithecus/Dinopithecus_Character_BP.Dinopithecus_Character_BP'"),
    'Diplocaulus': ('Diplocaulus_Character_BP_C', 'Diplocaulus', "Blueprint'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP.Diplocaulus_Character_BP'"),
    'Diplodocus': ('Diplodocus_Character_BP_C', 'Diplo', "Blueprint'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP.Diplodocus_Character_BP'"),
    'Dire Bear': ('Direbear_Character_BP_C', 'Direbear', "Blueprint'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP.Direbear_Character_BP'"),
    'Direwolf': ('Direwolf_Character_BP_C', 'Direwolf', "Blueprint'/Game/PrimalEarth/Dinos/Direwolf/Direwolf_Character_BP.Direwolf_Character_BP'"),
    'Dodo': ('Dodo_Character_BP_C', 'Dodo', "Blueprint'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP.Dodo_Character_BP'"),
    'DodoRex': ('DodoRex_Character_BP_C', 'DodoRex', "Blueprint'/Game/PrimalEarth/Dinos/DodoRex/DodoRex_Character_BP.DodoRex_Character_BP'"),
    'Doedicurus': ('Doed_Character_BP_C', 'Doed', "Blueprint'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP.Doed_Character_BP'"),
    'Dreadnoughtus': ('Dreadnoughtus_Character_BP_C', 'Dreadnoughtus', "Blueprint'/Game/ASA/Dinos/Dreadnoughtus/Dreadnoughtus_Character_BP.Dreadnoughtus_Character_BP'"),
    'Dung Beetle': ('DungBeetle_Character_BP_C', 'Beetle', "Blueprint'/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_Character_BP.DungBeetle_Character_BP'"),
    'Dunkleosteus': ('Dunkle_Character_BP_C', 'Dunkle', "Blueprint'/Game/PrimalEarth/Dinos/Dunkleosteus/Dunkle_Character_BP.Dunkle_Character_BP'"),
    'Electrophorus': ('Eel_Character_BP_C', 'Eel', "Blueprint'/Game/PrimalEarth/Dinos/Eel/Eel_Character_BP.Eel_Character_BP'"),
    'Ember Crystal Wyvern': ('CrystalWyvern_Character_BP_Ember_C', 'Wyvern', "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_Ember.CrystalWyvern_Character_BP_Ember'"),
    'Equus': ('Equus_Character_BP_C', 'Equus', "Blueprint'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP.Equus_Character_BP'"),
    'Fasolasuchus': ('Fasola_Character_BP_C', 'Fasola', "Blueprint'/Game/ASA/Dinos/Fasolasuchus/Fasola_Character_BP.Fasola_Character_BP'"),
    'Featherlight': ('LanternBird_Character_BP_C', 'Lantern Bird', "Blueprint'/Game/Aberration/Dinos/LanternBird/LanternBird_Character_BP.LanternBird_Character_BP'"),
    'Ferox': ('Shapeshifter_Small_Character_BP_C', 'Gremlin', "Blueprint'/Game/Genesis/Dinos/Shapeshifter/Shapeshifter_Small/Shapeshifter_Small_Character_BP.Shapeshifter_Small_Character_BP'"),
    'Fire Wyvern': ('Wyvern_Character_BP_Fire_C', 'Wyvern', "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Fire.Wyvern_Character_BP_Fire'"),
    'Fjordhawk': ('Fjordhawk_Character_BP_C', 'Fjordhawk', "Blueprint'/Game/Fjordur/Dinos/Fjordhawk/Fjordhawk_Character_BP.Fjordhawk_Character_BP'"),
    'Gacha': ('Gacha_Character_BP_C', 'Gacha', "Blueprint'/Game/Extinction/Dinos/Gacha/Gacha_Character_BP.Gacha_Character_BP'"),
    'Gallimimus': ('Galli_Character_BP_C', 'Galli', "Blueprint'/Game/PrimalEarth/Dinos/Gallimimus/Galli_Character_BP.Galli_Character_BP'"),
    'Gasbags': ('GasBags_Character_BP_C', 'GasBags', "Blueprint'/Game/Extinction/Dinos/GasBag/GasBags_Character_BP.GasBags_Character_BP'"),
    'Giant Bee': ('Bee_Character_BP_C', 'Bee', "Blueprint'/Game/PrimalEarth/Dinos/Bee/Bee_Character_BP.Bee_Character_BP'"),
    'Giganotosaurus': ('Gigant_Character_BP_C', 'Gigant', "Blueprint'/Game/PrimalEarth/Dinos/Giganotosaurus/Gigant_Character_BP.Gigant_Character_BP'"),
    'Gigantopithecus': ('Bigfoot_Character_BP_C', 'Bigfoot', "Blueprint'/Game/PrimalEarth/Dinos/Bigfoot/Bigfoot_Character_BP.Bigfoot_Character_BP'"),
    'Gigantoraptor': ('Gigantoraptor_Character_BP_C', 'Gigantoraptor', "Blueprint'/Game/ASA/Dinos/Gigantoraptor/Gigantoraptor_Character_BP.Gigantoraptor_Character_BP'"),
    'Glowtail': ('LanternLizard_Character_BP_C', 'Lantern Lizard', "Blueprint'/Game/Aberration/Dinos/LanternLizard/LanternLizard_Character_BP.LanternLizard_Character_BP'"),
    'Griffin': ('Griffin_Character_BP_C', 'Griffin', "Blueprint'/Game/PrimalEarth/Dinos/Griffin/Griffin_Character_BP.Griffin_Character_BP'"),
    'Helicoprion': ('Helicoprion_Character_BP_C', 'Helicoprion', "Blueprint'/Game/ASA/Dinos/Helicoprion/Helicoprion_Character_BP.Helicoprion_Character_BP'"),
    'Hesperornis': ('Hesperornis_Character_BP_C', 'Hesperornis', "Blueprint'/Game/PrimalEarth/Dinos/Hesperornis/Hesperornis_Character_BP.Hesperornis_Character_BP'"),
    'Hyaenodon': ('Hyaenodon_Character_BP_C', 'Hyaenodon', "Blueprint'/Game/PrimalEarth/Dinos/Hyaenodon/Hyaenodon_Character_BP.Hyaenodon_Character_BP'"),
    'Ice Wyvern': ('Wyvern_Character_BP_Ice_C', 'Wyvern', "Blueprint'/Game/ASA/Dinos/IceWyvern/Wyvern_Character_BP_Ice.Wyvern_Character_BP_Ice'"),
    'Ichthyornis': ('Ichthyornis_Character_BP_C', 'Ichthyornis', "Blueprint'/Game/PrimalEarth/Dinos/Ichthyornis/Ichthyornis_Character_BP.Ichthyornis_Character_BP'"),
    'Ichthyosaurus': ('Dolphin_Character_BP_C', 'Dolphin', "Blueprint'/Game/PrimalEarth/Dinos/Dolphin/Dolphin_Character_BP.Dolphin_Character_BP'"),
    'Iguanodon': ('Iguanodon_Character_BP_C', 'Iguanodon', "Blueprint'/Game/PrimalEarth/Dinos/Iguanodon/Iguanodon_Character_BP.Iguanodon_Character_BP'"),
    'Jerboa': ('Jerboa_Character_BP_C', 'Jerboa', "Blueprint'/Game/ScorchedEarth/Dinos/Jerboa/Jerboa_Character_BP.Jerboa_Character_BP'"),
    'Kairuku': ('Kairuku_Character_BP_C', 'Kairu', "Blueprint'/Game/PrimalEarth/Dinos/Kairuku/Kairuku_Character_BP.Kairuku_Character_BP'"),
    'Kaprosuchus': ('Kaprosuchus_Character_BP_C', 'Kaprosuchus', "Blueprint'/Game/PrimalEarth/Dinos/Kaprosuchus/Kaprosuchus_Character_BP.Kaprosuchus_Character_BP'"),
    'Karkinos': ('Crab_Character_BP_C', 'CaveCrab', "Blueprint'/Game/Aberration/Dinos/Crab/Crab_Character_BP.Crab_Character_BP'"),
    'Kentrosaurus': ('Kentro_Character_BP_C', 'Kentro', "Blueprint'/Game/PrimalEarth/Dinos/Kentrosaurus/Kentro_Character_BP.Kentro_Character_BP'"),
    'Leedsichthys': ('Leedsichthys_Character_BP_C', 'Leedsichthys', "Blueprint'/Game/PrimalEarth/Dinos/Leedsichthys/Leedsichthys_Character_BP.Leedsichthys_Character_BP'"),
    'Lightning Wyvern': ('Wyvern_Character_BP_Lightning_C', 'Wyvern', "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Lightning.Wyvern_Character_BP_Lightning'"),
    'Liopleurodon': ('Liopleurodon_Character_BP_C', 'Liopleurodon', "Blueprint'/Game/PrimalEarth/Dinos/Liopleurodon/Liopleurodon_Character_BP.Liopleurodon_Character_BP'"),
    'Lymantria': ('Moth_Character_BP_C', 'Moth', "Blueprint'/Game/ScorchedEarth/Dinos/Moth/Moth_Character_BP.Moth_Character_BP'"),
    'Lystrosaurus': ('Lystro_Character_BP_C', 'Lystro', "Blueprint'/Game/PrimalEarth/Dinos/Lystrosaurus/Lystro_Character_BP.Lystro_Character_BP'"),
    'Maewing': ('MilkGlider_Character_BP_C', 'Maewing', "Blueprint'/Game/Genesis2/Dinos/MilkGlider/MilkGlider_Character_BP.MilkGlider_Character_BP'"),
    'Magmasaur': ('Cherufe_Character_BP_C', 'LavaLizard', "Blueprint'/Game/Genesis/Dinos/Cherufe/Cherufe_Character_BP.Cherufe_Character_BP'"),
    'Mammoth': ('Mammoth_Character_BP_C', 'Mammoth', "Blueprint'/Game/PrimalEarth/Dinos/Mammoth/Mammoth_Character_BP.Mammoth_Character_BP'"),
    'Managarmr': ('IceJumper_Character_BP_C', 'Managarmr', "Blueprint'/Game/Extinction/Dinos/IceJumper/IceJumper_Character_BP.IceJumper_Character_BP'"),
    'Manta': ('Manta_Character_BP_C', 'Manta', "Blueprint'/Game/PrimalEarth/Dinos/Manta/Manta_Character_BP.Manta_Character_BP'"),
    'Mantis': ('Mantis_Character_BP_C', 'Mantis', "Blueprint'/Game/ScorchedEarth/Dinos/Mantis/Mantis_Character_BP.Mantis_Character_BP'"),
    'Megachelon': ('GiantTurtle_Character_BP_C', 'GiantTurtle', "Blueprint'/Game/Genesis/Dinos/GiantTurtle/GiantTurtle_Character_BP.GiantTurtle_Character_BP'"),
    'Megalania': ('Megalania_Character_BP_C', 'Megalania', "Blueprint'/Game/PrimalEarth/Dinos/Megalania/Megalania_Character_BP.Megalania_Character_BP'"),
    'Megaloceros': ('Stag_Character_BP_C', 'Stag', "Blueprint'/Game/PrimalEarth/Dinos/Stag/Stag_Character_BP.Stag_Character_BP'"),
    'Megalodon': ('Megalodon_Character_BP_C', 'Mega', "Blueprint'/Game/PrimalEarth/Dinos/Megalodon/Megalodon_Character_BP.Megalodon_Character_BP'"),
    'Megalosaurus': ('Megalosaurus_Character_BP_C', 'Megalosaurus', "Blueprint'/Game/PrimalEarth/Dinos/Megalosaurus/Megalosaurus_Character_BP.Megalosaurus_Character_BP'"),
    'Meganeura': ('Dragonfly_Character_BP_C', 'Dragonfly', "Blueprint'/Game/PrimalEarth/Dinos/Dragonfly/Dragonfly_Character_BP.Dragonfly_Character_BP'"),
    'Megaraptor': ('ValMegaraptor_Character_BP_C', 'Megaraptor', "Blueprint'/Game/ASA/Dinos/Megaraptor/ValMegaraptor_Character_BP.ValMegaraptor_Character_BP'"),
    'Megatherium': ('Megatherium_Character_BP_C', 'Megatherium', "Blueprint'/Game/PrimalEarth/Dinos/Megatherium/Megatherium_Character_BP.Megatherium_Character_BP'"),
    'Mesopithecus': ('Monkey_Character_BP_C', 'Monkey', "Blueprint'/Game/PrimalEarth/Dinos/Monkey/Monkey_Character_BP.Monkey_Character_BP'"),
    'Microraptor': ('Microraptor_Character_BP_C', 'Microraptor', "Blueprint'/Game/PrimalEarth/Dinos/Microraptor/Microraptor_Character_BP.Microraptor_Character_BP'"),
    'Morellatops': ('camelsaurus_Character_BP_C', 'Camelsaurus', "Blueprint'/Game/ScorchedEarth/Dinos/Camelsaurus/camelsaurus_Character_BP.camelsaurus_Character_BP'"),
    'Mosasaurus': ('Mosa_Character_BP_C', 'Mosasaur', "Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP.Mosa_Character_BP'"),
    'Moschops': ('Moschops_Character_BP_C', 'Moschops', "Blueprint'/Game/PrimalEarth/Dinos/Moschops/Moschops_Character_BP.Moschops_Character_BP'"),
    'Noglin': ('BrainSlug_Character_BP_C', 'BrainSlug', "Blueprint'/Game/Genesis2/Dinos/BrainSlug/BrainSlug_Character_BP.BrainSlug_Character_BP'"),
    'Onyc': ('Bat_Character_BP_C', 'Bat', "Blueprint'/Game/PrimalEarth/Dinos/Bat/Bat_Character_BP.Bat_Character_BP'"),
    'Otter': ('Otter_Character_BP_C', 'Otter', "Blueprint'/Game/PrimalEarth/Dinos/Otter/Otter_Character_BP.Otter_Character_BP'"),
    'Oviraptor': ('Oviraptor_Character_BP_C', 'Ovi', "Blueprint'/Game/PrimalEarth/Dinos/Oviraptor/Oviraptor_Character_BP.Oviraptor_Character_BP'"),
    'Ovis': ('Sheep_Character_BP_C', 'Sheep', "Blueprint'/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP.Sheep_Character_BP'"),
    'Pachy': ('Pachy_Character_BP_C', 'Pachy', "Blueprint'/Game/PrimalEarth/Dinos/Pachy/Pachy_Character_BP.Pachy_Character_BP'"),
    'Pachyrhinosaurus': ('Pachyrhino_Character_BP_C', 'Pachyrhinosaurus', "Blueprint'/Game/PrimalEarth/Dinos/Pachyrhinosaurus/Pachyrhino_Character_BP.Pachyrhino_Character_BP'"),
    'Paraceratherium': ('Paracer_Character_BP_C', 'Paracer', "Blueprint'/Game/PrimalEarth/Dinos/Paraceratherium/Paracer_Character_BP.Paracer_Character_BP'"),
    'Parasaur': ('Para_Character_BP_C', 'Para', "Blueprint'/Game/PrimalEarth/Dinos/Para/Para_Character_BP.Para_Character_BP'"),
    'Pegomastax': ('Pegomastax_Character_BP_C', 'Pegomastax', "Blueprint'/Game/PrimalEarth/Dinos/Pegomastax/Pegomastax_Character_BP.Pegomastax_Character_BP'"),
    'Pelagornis': ('Pela_Character_BP_C', 'Pela', "Blueprint'/Game/PrimalEarth/Dinos/Pelagornis/Pela_Character_BP.Pela_Character_BP'"),
    'Phiomia': ('Phiomia_Character_BP_C', 'Phiomia', "Blueprint'/Game/PrimalEarth/Dinos/Phiomia/Phiomia_Character_BP.Phiomia_Character_BP'"),
    'Phoenix': ('Phoenix_Character_BP_C', 'Phoenix', "Blueprint'/Game/ScorchedEarth/Dinos/Phoenix/Phoenix_Character_BP.Phoenix_Character_BP'"),
    'Piranha': ('Piranha_Character_BP_C', 'Piranha', "Blueprint'/Game/PrimalEarth/Dinos/Piranha/Piranha_Character_BP.Piranha_Character_BP'"),
    'Plesiosaur': ('Plesiosaur_Character_BP_C', 'Plesiosaur', "Blueprint'/Game/PrimalEarth/Dinos/Plesiosaur/Plesiosaur_Character_BP.Plesiosaur_Character_BP'"),
    'Poison Wyvern': ('Wyvern_Character_BP_Poison_C', 'Wyvern', "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Poison.Wyvern_Character_BP_Poison'"),
    'Procoptodon': ('Procoptodon_Character_BP_C', 'Kangaroo', "Blueprint'/Game/PrimalEarth/Dinos/Procoptodon/Procoptodon_Character_BP.Procoptodon_Character_BP'"),
    'Pteranodon': ('Ptero_Character_BP_C', 'Ptera', "Blueprint'/Game/PrimalEarth/Dinos/Ptero/Ptero_Character_BP.Ptero_Character_BP'"),
    'Pulmonoscorpius': ('Scorpion_Character_BP_C', 'Scorpion', "Blueprint'/Game/PrimalEarth/Dinos/Scorpion/Scorpion_Character_BP.Scorpion_Character_BP'"),
    'Purlovia': ('Purlovia_Character_BP_C', 'Purlovia', "Blueprint'/Game/PrimalEarth/Dinos/Purlovia/Purlovia_Character_BP.Purlovia_Character_BP'"),
    'Pyromane': ('FireLion_Character_BP_C', 'FireLion', "Blueprint'/Game/ASA/Dinos/FireLion/FireLion_Character_BP.FireLion_Character_BP'"),
    'Quetzal': ('Quetz_Character_BP_C', 'Quetz', "Blueprint'/Game/PrimalEarth/Dinos/Quetzalcoatlus/Quetz_Character_BP.Quetz_Character_BP'"),
    'R-Reaper King': ('Xenomorph_Character_BP_Male_Gen2_C', 'Xenomorph', "Blueprint'/Game/Genesis2/Dinos/BiomeVariants/Xenomorph_Character_BP_Male_Gen2.Xenomorph_Character_BP_Male_Gen2'"),
    'Raptor': ('Raptor_Character_BP_C', 'Raptor', "Blueprint'/Game/PrimalEarth/Dinos/Raptor/Raptor_Character_BP.Raptor_Character_BP'"),
    'Ravager': ('CaveWolf_Character_BP_C', 'CaveWolf', "Blueprint'/Game/Aberration/Dinos/CaveWolf/CaveWolf_Character_BP.CaveWolf_Character_BP'"),
    'Reaper King': ('Xenomorph_Character_BP_Male_C', 'Xenomorph', "Blueprint'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Male.Xenomorph_Character_BP_Male'"),
    'Rex': ('Rex_Character_BP_C', 'Rex', "Blueprint'/Game/PrimalEarth/Dinos/Rex/Rex_Character_BP.Rex_Character_BP'"),
    'Rhyniognatha': ('Rhynio_Character_BP_C', 'Rhynio', "Blueprint'/Game/PrimalEarth/Dinos/Rhyniognatha/Rhynio_Character_BP.Rhynio_Character_BP'"),
    'Rock Drake': ('RockDrake_Character_BP_C', 'RockDrake', "Blueprint'/Game/Aberration/Dinos/RockDrake/RockDrake_Character_BP.RockDrake_Character_BP'"),
    'Rock Elemental': ('RockGolem_Character_BP_C', 'RockElemental', "Blueprint'/Game/ScorchedEarth/Dinos/RockGolem/RockGolem_Character_BP.RockGolem_Character_BP'"),
    'Roll Rat': ('MoleRat_Character_BP_C', 'MoleRat', "Blueprint'/Game/Aberration/Dinos/MoleRat/MoleRat_Character_BP.MoleRat_Character_BP'"),
    'Sabertooth': ('Saber_Character_BP_C', 'Sabertooth', "Blueprint'/Game/PrimalEarth/Dinos/Saber/Saber_Character_BP.Saber_Character_BP'"),
    'Sabertooth Salmon': ('Salmon_Character_BP_C', 'Salmon', "Blueprint'/Game/PrimalEarth/Dinos/Salmon/Salmon_Character_BP.Salmon_Character_BP'"),
    'Sarco': ('Sarco_Character_BP_C', 'Sarco', "Blueprint'/Game/PrimalEarth/Dinos/Sarco/Sarco_Character_BP.Sarco_Character_BP'"),
    'Shadowmane': ('LionfishLion_Character_BP_C', 'Lionfish Lion', "Blueprint'/Game/Genesis2/Dinos/LionfishLion/LionfishLion_Character_BP.LionfishLion_Character_BP'"),
    'Shastasaurus': ('Shastasaurus_Character_BP_C', 'Shasta', "Blueprint'/Game/ASA/Dinos/Shastasaurus/Shastasaurus_Character_BP.Shastasaurus_Character_BP'"),
    'Shinehorn': ('LanternGoat_Character_BP_C', 'Lantern Goat', "Blueprint'/Game/Aberration/Dinos/LanternGoat/LanternGoat_Character_BP.LanternGoat_Character_BP'"),
    'Sinomacrops': ('Sinomacrops_Character_BP_C', 'Sino', "Blueprint'/Game/LostIsland/Dinos/Sinomacrops/Sinomacrops_Character_BP.Sinomacrops_Character_BP'"),
    'Snow Owl': ('Owl_Character_BP_C', 'Owl', "Blueprint'/Game/Extinction/Dinos/Owl/Owl_Character_BP.Owl_Character_BP'"),
    'Spino': ('Spino_Character_BP_C', 'Spino', "Blueprint'/Game/PrimalEarth/Dinos/Spino/Spino_Character_BP.Spino_Character_BP'"),
    'Stegosaurus': ('Stego_Character_BP_C', 'Stego', "Blueprint'/Game/PrimalEarth/Dinos/Stego/Stego_Character_BP.Stego_Character_BP'"),
    'Tapejara': ('Tapejara_Character_BP_C', 'Tapejara', "Blueprint'/Game/PrimalEarth/Dinos/Tapejara/Tapejara_Character_BP.Tapejara_Character_BP'"),
    'Tek Rex': ('BionicRex_Character_BP_C', 'Rex', "Blueprint'/Game/PrimalEarth/Dinos/Rex/BionicRex_Character_BP.BionicRex_Character_BP'"),
    'Tek Stryder': ('TekStrider_Character_BP_C', 'TekStrider', "Blueprint'/Game/Genesis2/Dinos/TekStrider/TekStrider_Character_BP.TekStrider_Character_BP'"),
    'Terror Bird': ('TerrorBird_Character_BP_C', 'TerrorBird', "Blueprint'/Game/PrimalEarth/Dinos/TerrorBird/TerrorBird_Character_BP.TerrorBird_Character_BP'"),
    'Therizinosaur': ('Therizino_Character_BP_C', 'Therizinosaurus', "Blueprint'/Game/PrimalEarth/Dinos/Therizinosaurus/Therizino_Character_BP.Therizino_Character_BP'"),
    'Thorny Dragon': ('SpineyLizard_Character_BP_C', 'SpineyLizard', "Blueprint'/Game/ScorchedEarth/Dinos/SpineyLizard/SpineyLizard_Character_BP.SpineyLizard_Character_BP'"),
    'Thylacoleo': ('Thylacoleo_Character_BP_C', 'Thylacoleo', "Blueprint'/Game/PrimalEarth/Dinos/Thylacoleo/Thylacoleo_Character_BP.Thylacoleo_Character_BP'"),
    'Titanoboa': ('BoaFrill_Character_BP_C', 'TitanBoa', "Blueprint'/Game/PrimalEarth/Dinos/BoaFrill/BoaFrill_Character_BP.BoaFrill_Character_BP'"),
    'Titanosaur': ('Titanosaur_Character_BP_C', 'Titan', "Blueprint'/Game/PrimalEarth/Dinos/titanosaur/Titanosaur_Character_BP.Titanosaur_Character_BP'"),
    'Triceratops': ('Trike_Character_BP_C', 'Trike', "Blueprint'/Game/PrimalEarth/Dinos/Trike/Trike_Character_BP.Trike_Character_BP'"),
    'Trilobite': ('Trilobite_Character_C', 'Trilobite', "Blueprint'/Game/PrimalEarth/Dinos/Trilobite/Trilobite_Character.Trilobite_Character'"),
    'Troodon': ('Troodon_Character_BP_C', 'Troodon', "Blueprint'/Game/PrimalEarth/Dinos/Troodon/Troodon_Character_BP.Troodon_Character_BP'"),
    'Tropeognathus': ('Tropeognathus_Character_BP_C', 'Tropeognathus', "Blueprint'/Game/PrimalEarth/Dinos/Tropeognathus/Tropeognathus_Character_BP.Tropeognathus_Character_BP'"),
    'Tropical Crystal Wyvern': ('CrystalWyvern_Character_BP_WS_C', 'Wyvern', "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalWyvern_Character_BP_WS.CrystalWyvern_Character_BP_WS'"),
    'Tusoteuthis': ('Tusoteuthis_Character_BP_C', 'Tusoteuthis', "Blueprint'/Game/PrimalEarth/Dinos/Tusoteuthis/Tusoteuthis_Character_BP.Tusoteuthis_Character_BP'"),
    'Velonasaur': ('Spindles_Character_BP_C', 'Velonasaur', "Blueprint'/Game/Extinction/Dinos/Spindles/Spindles_Character_BP.Spindles_Character_BP'"),
    'Voidwyrm': ('TekWyvern_Character_BP_C', 'TekWyvern', "Blueprint'/Game/Genesis2/Dinos/TekWyvern/TekWyvern_Character_BP.TekWyvern_Character_BP'"),
    'Woolly Rhino': ('Rhino_Character_BP_C', 'Rhino', "Blueprint'/Game/PrimalEarth/Dinos/WoollyRhino/Rhino_Character_BP.Rhino_Character_BP'"),
    'Wyvern': ('Wyvern_Character_BP_Base_C', 'Wyvern', "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Base.Wyvern_Character_BP_Base'"),
    'X-Rex': ('Volcano_Rex_Character_BP_C', 'Rex', "Blueprint'/Game/Genesis/Dinos/BiomeVariants/Volcano_Rex/Volcano_Rex_Character_BP.Volcano_Rex_Character_BP'"),
    'X-Spino': ('Bog_Spino_Character_BP_C', 'Spino', "Blueprint'/Game/Genesis/Dinos/BiomeVariants/Bog_Spino/Bog_Spino_Character_BP.Bog_Spino_Character_BP'"),
    'Yi Ling': ('YiLing_Character_BP_C', 'YiLing', "Blueprint'/Game/ASA/Dinos/YiLing/YiLing_Character_BP.YiLing_Character_BP'"),
    'Yutyrannus': ('Yutyrannus_Character_BP_C', 'Yutyrannus', "Blueprint'/Game/PrimalEarth/Dinos/Yutyrannus/Yutyrannus_Character_BP.Yutyrannus_Character_BP'"),
}

_CREATURE_NAMES_SORTED: list[str] = sorted(_CREATURE_DATA.keys())

# Reverse lookups
_ENTITY_ID_TO_NAME: dict[str, str] = {v[0]: k for k, v in _CREATURE_DATA.items() if v[0]}
_NAMETAG_TO_NAMES: dict[str, list[str]] = {}
for _cn, _cv in _CREATURE_DATA.items():
    if _cv[1]:
        _NAMETAG_TO_NAMES.setdefault(_cv[1], []).append(_cn)
